%% Braking System
clear; clc;

%% === INPUT DATA ===

pedal_force = 314;               % [N] Force applied by the driver on the pedal
lever_ratio = 2.6;               % Brake pedal lever ratio
bias_bar_ratio = 0.67;           % [%] Bias bar distribution (0.5 = 50% front)

mu = 0.8;                        % Pad friction coefficient

% Master cylinder diameters [mm]
d_mc_front = 15.875;
d_mc_rear = 17.78;

% Caliper pistons [mm]
d_piston_front = 24; n_pistons_front = 4;
d_piston_rear = 24; n_pistons_rear = 4;

% Average pad radius on disc [mm]
r_disk_front = 99.5;
r_disk_rear = 99.5;

% Number of calipers per axle
n_calipers_front = 2;
n_calipers_rear = 2;

%% === CALCULATIONS ===

% Conversion from diameter to area [m^2]
d2A = @(d_mm) pi * (d_mm * 1e-3 / 2)^2;

A_mc_front = d2A(d_mc_front);
A_mc_rear = d2A(d_mc_rear);

F_lever = pedal_force * lever_ratio;

% Forces applied to master cylinders
F_mc_front = F_lever * bias_bar_ratio;
F_mc_rear = F_lever * (1 - bias_bar_ratio);

% Pressure in circuits [Pa]
P_front = F_mc_front / A_mc_front;
P_rear = F_mc_rear / A_mc_rear;

% Total caliper piston areas
A_pistons_front = n_pistons_front * d2A(d_piston_front);
A_pistons_rear = n_pistons_rear * d2A(d_piston_rear);

% Forces generated by calipers [N]
F_calipers_front = P_front * A_pistons_front * n_calipers_front;
F_calipers_rear = P_rear * A_pistons_rear * n_calipers_rear;

% Braking torque [Nm]
M_front = F_calipers_front * (r_disk_front * 1e-3);
M_rear = F_calipers_rear * (r_disk_rear * 1e-3);

% Torque per single caliper
M_caliper_front = M_front / n_calipers_front;
M_caliper_rear = M_rear / n_calipers_rear;

% Normal forces (caliper clamp force)
F_normal_front = F_calipers_front / n_calipers_front;
F_normal_rear = F_calipers_rear / n_calipers_rear;

% Tangential forces (friction at pads)
F_tangential_front = mu * F_normal_front;
F_tangential_rear = mu * F_normal_rear;

% Brake bias
bias = M_front / (M_front + M_rear) * 100;

%% === OUTPUT ===
fprintf('=== BRAKING SYSTEM OUTPUT ===\n');
fprintf('Front circuit pressure: %.1f bar\n', P_front / 1e5);
fprintf('Rear circuit pressure: %.1f bar\n', P_rear / 1e5);
fprintf('Total front caliper force: %.1f N\n', F_calipers_front);
fprintf('Total rear caliper force: %.1f N\n', F_calipers_rear);
fprintf('Front braking torque: %.1f Nm\n', M_front);
fprintf('Rear braking torque: %.1f Nm\n', M_rear);
fprintf('Braking torque per front caliper: %.1f Nm\n', M_caliper_front);
fprintf('Braking torque per rear caliper: %.1f Nm\n', M_caliper_rear);
fprintf('Tangential force (front caliper): %.1f N\n', F_tangential_front);
fprintf('Tangential force (rear caliper): %.1f N\n', F_tangential_rear);
fprintf('Brake bias: %.1f%% front / %.1f%% rear\n', bias, 100 - bias);
